### ISSUE TITLE
UnhandledPromiseException error is not defined

### ISSUE THREAD

**Issue by tarunwadhwa-paypay** [adrianjost/files-sync-action#139]
Hi, 

While running this action, I sometimes get this exception

```
FILE_PATTERNS [
46
(node:1769) UnhandledPromiseRejectionWarning: ReferenceError: error is not defined
47
  "/.github\\/workflows\\/start_release\\.yaml$/",
48
    at Object.E [as commitAll] (/home/runner/work/_actions/adrianjost/files-sync-action/master/dist/index.js:1:66500)
49
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
50
    at async /home/runner/work/_actions/adrianjost/files-sync-action/master/dist/index.js:1:64599
51
  "/.github\\/workflows\\/sync_test\\.yaml$/"
52
    at async Promise.all (index 0)
53
    at async p (/home/runner/work/_actions/adrianjost/files-sync-action/master/dist/index.js:1:64298)
54
(node:1769) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
55
]
```

The strange thing is that changes are getting committed just fine. But want to understand if this error is anyway affecting us

Any Idea, what can cause this?

**Comment by adrianjost** [comment]
Unfortunately not at the moment. I would guess that it has to do with the command line commands I'm executing for git. It's always a bit tricky handling those.
Could you give me a larger part of the logs, so I can guess with a bit more context?

Or even better take a look yourself with debug logs enabled. They should provide more details.
https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging
