### ISSUE TITLE
Action fails when forced to run on newer version of Node

### ISSUE THREAD

**Issue by GaryJones** [adrianjost/files-sync-action#233]
I had a Sync workflow [fail](https://github.com/Automattic/wpvip-plugins-.github/actions/runs/5670862203/job/15366699636) today, with the following message:

> Sync GitHub Actions workflows
> The following actions uses node12 which is deprecated and will be forced to run on node16: adrianjost/files-sync-action@v1.5.1. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

Could the action be updated to run with a newer version of Node please, @adrianjost?

**Comment by adrianjost** [comment]
Please check out https://github.com/adrianjost/files-sync-action/releases/tag/v2.0.0

**Comment by GaryJones** [comment]
Thank you - I appreciate the quick resolution!

**Comment by adrianjost** [comment]
Sure, I hope it works. Your CI run seems to be failing. Similar to the deployment CI action in this repo. I hadn't had time to figure out a fix for that yet. Let me know if theres more I need to do in this repo. Haven't worked on it for a while and the documentation could have be better 😬.

**Comment by GaryJones** [comment]
I had the one failure before I reported the issue (but then other successful runs before the fix), then another failure when I updated the version to "v2", but successful runs since I changed the version to "v2.0.0" - not sure why it needed to be so picky. 

Otherwise, it seems to work exactly as intended! Thank you!
