### ISSUE TITLE
Error: Command failed: git update-index --really-refresh

### ISSUE THREAD

**Issue by schlessera** [adrianjost/files-sync-action#239]
The PR #237 included with release 2.0.1 has broken the CI on the https://github.com/wp-cli organization: https://github.com/wp-cli/.github/actions/runs/5725366770/job/15513736962#step:2:206

![Sync GitHub Actions workflows · wp-cli_ 2023-08-01 at 12 12 05 PM github@cda4ec8 - Google Chrome](https://github.com/adrianjost/files-sync-action/assets/83631/0e9e11dc-0563-4cfa-8c5c-31acdc4c9814)

It looks like the newly added command is being run outside of a repository:
```
fatal: not a git repository (or any of the parent directories): .git
```

This was working fine with release 2.0.0 before, and reverting the bump to 2.0.1 fixed the broken CI again.

**Comment by adrianjost** [comment]
Thank you for bringing this up. A fix has been pushed as 2.0.2 to the repo. Please let me know if this fixes your issue.
