### ISSUE TITLE
Add Option to specify src & target roots

### ISSUE THREAD

**Issue by adrianjost** [adrianjost/files-sync-action#27]
I want to sync files from `RepoA/dir1` into `Repo[B-Z]/dir2`. There is no need to define the root for each `TARGET_REPO` seperately.

- [ ] Add `SRC_ROOT` option wich defaults to `/`
- [ ] Add `TARGET_ROOT` option wich defaults to `/`
- [ ] The RegExp should start matching after the defined root directory

**Comment by phnx47** [comment]
@adrianjost  Any news about this feature?

**Comment by adrianjost** [comment]
Not yet, cause it was a feature I personally hadn't had a use-case for. But it shouldn't be too difficult to implement. Maybe I find some time after Christmas to implement this now someone seems to have the need for this.
But if you wan't you could also open up a PR, I can't give any guarantees when this is feature will be ready.

**Comment by phnx47** [comment]
@adrianjost It is ok! Thank you! I already found solution for this in another action. I can use two actions for my projects. Maybe I will try implement it myself too.

**Comment by adrianjost** [comment]
@phnx47 it's now implemented and I will publish a release for it soon.
