### ISSUE TITLE
Update action to use node 20

### ISSUE THREAD

**Issue by wojsmol** [adrianjost/files-sync-action#282]
Hi
Please update this action to use node 20 - https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

**Comment by adrianjost** [comment]
I'm happy to review a pull request for that. Unfortunately I currently don't have time to do so myself.

**Comment by wojsmol** [comment]
@adrianjost If this is only `action.yml` change then I can send a PR.

**Comment by adrianjost** [comment]
I actually don't know, haven't touched actions code for at least a year. But possibly yes.
